[package]
name = "espygarten"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
espy.path = "../espy"
espystandard.path = "../espystandard"
wasm-bindgen = "0.2.100"
