[package]
name = "espy-ears"
version = "0.1.0"
edition = "2024"

[dependencies]
dst-factory = { git = "ssh://git@github.com/evie-calico/dst-factory" }
espy-eyes.path = "../espy-eyes"

[lints]
workspace = true
